title: Data Mango
description: "CSP Tri 3 Project"
owner_name: Trevor Vick
github_username: Tvick22
github_repo: "DataMango"
baseurl: "/DataMango"
colors:
  primary: "#FF9F1C" # Mango Orange
  primary-hover: "#e88d15"
  secondary: "#015A65" # Deep Teal
  secondary-hover: "#01404a"
  background: "#FAFAF8" # Off-White
  text: "#333333" # Charcoal Gray
  red: "#F25C54" # Coral Red
  accent:
    green: "#007F5F" # Forest Green
    green-hover: "#006b50"
    red: "#F25C54" # Coral Red
    red-hover: "#e04d48"
  neutral: "#F4E8C1" # Soft Beige
header_pages:
  - browse-documentation.md
  - contact.md
  - admin/dashboard.md
  - create-review.md
  - review_map.md
  - navigation/authentication/login.md
